spring:
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: create

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/bezrukiy?currentSchema=dev
    username: dev
    password: dev

#files:
#  logo: ${bezrukiy.files.logos}
#  image: ${bezrukiy.files.images}
#  info: ${bezrukiy.files.infos}

files:
  logo: D:/files/
  image: D:/files/
  info: D:/files/