#Развертывание БД в Docker.
version: "3"

services:
  postgres:
    image: "postgres:latest"
    container_name: "postgres-bezrukiy_dev"
    ports:
      - 5432:5432
    environment:
      - "POSTGRES_USER=dev"
      - "POSTGRES_PASSWORD=dev"
      - "POSTGRES_HOST_AUTH_METHOD=trust"
      - "POSTGRES_DB=bezrukiy"